In [2]:
import yfinance as yf

In [3]:
tsla = yf.Ticker("TSLA")

In [7]:
hist = tsla.history(period="1y")

In [8]:
hist

              Open    High     Low   Close     Volume  Dividends  Stock Splits
Date
2019-09-16   49.20   49.49   48.23   48.56   23640500          0           0.0
2019-09-17   48.49   49.12   48.07   48.96   19327000          0           0.0
2019-09-18   49.00   49.63   48.47   48.70   20851000          0           0.0
2019-09-19   49.20   49.59   48.97   49.32   23979000          0           0.0
2019-09-20   49.30   49.39   47.63   48.12   31765000          0           0.0
...            ...     ...     ...     ...        ...        ...           ...
2020-09-08  356.00  368.74  329.88  330.21  115465700          0           0.0
2020-09-09  356.60  369.00  341.51  366.28   79465800          0           0.0
2020-09-10  386.21  398.99  360.56  371.34   84930600          0           0.0
2020-09-11  381.94  382.50  360.50  372.72   60478200          0           0.0
2020-09-14  380.95  410.80  373.30  409.48   67999010          0           0.0

[252 rows x 7 columns]